name: detour_flutter_plugin
description: "Flutter bridge SDK for Detour deferred deep links and analytics."
version: 1.0.0
homepage: https://docs.swmansion.com/detour/docs/sdk/flutter/sdk-installation
repository: https://github.com/software-mansion-labs/detour-flutter-plugin
issue_tracker: https://github.com/software-mansion-labs/detour-flutter-plugin/issues
topics:
  - deep-links
  - deferred-deep-links
  - analytics
  - attribution

environment:
  sdk: ^3.11.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.swmansion.detour
        pluginClass: DetourFlutterPlugin
      ios:
        pluginClass: DetourFlutterPlugin
